### ISSUE TITLE
"no call signatures" TypeScript error

### ISSUE THREAD

**Issue by admehta01** [CharlesStover/fetch-action-creator#11]
Importing this way:
`import fetchActionCreator from 'fetch-action-creator';`

When I call `fetchActionCreator`, I get this TS error:
```
This expression is not callable.
  Type 'typeof import("[path]/node_modules/fetch-action-creator/fetch-action-creator")' has no call signatures.ts(2349
```

I'm on TS 3.6.3.

**Comment by quisido** [comment]
It is likely an issue that depends on TypeScript version. Try this:

```
import fetchActionCreator = require('fetch-action-creator');
```

Or try setting `compilerOptions.allowSyntheticDefaultImports` to `true` in `tsconfig.json`.

Let me know if you need further assistance.
